### ISSUE TITLE
타임리프를 사용하시는 이유가 뭔가요??

### ISSUE THREAD

**Issue by bbubbush** [jinsulog1/spring-board-api#2]
https://github.com/jinsulog1/spring-board-api/blob/8f3d3376e1dd37ff95ec8c0769143f4ba2f879b5/board/pom.xml#L22

서버구성하는데 화면개발은 필요 없을 것 같은데 사용하신 이유가 있나요??

**Comment by jinsulog1** [comment]
기본세팅 할 때 이것저것 검색 해보면서 참고하다보니 섞여서 들어간거같습니다!

**Comment by bbubbush** [comment]
넵 개발에 필요한거 아니면 빼고 갈게요 다음에 의존성 지우고 이슈 클로징 해주세요 ㅋㅋ
