### ISSUE TITLE
게시판 화면 사용여부 확인

### ISSUE THREAD

**Issue by bbubbush** [jinsulog1/spring-board-api#3]
https://github.com/jinsulog1/spring-board-api/blob/8f3d3376e1dd37ff95ec8c0769143f4ba2f879b5/board/src/main/webapp/index.html#L4

해당 과제는 프론트 개발 없이 서버만 개발하는 과제인데 혹시 테스트를 위해 화면이 필요하신가요??

**Comment by jinsulog1** [comment]
JSON형태로만 나오는 거지만 전체적인 틀이나 돌아가는 구조를 알고싶어서 시작할 때 테스트용으로 생성했었습니다

**Comment by bbubbush** [comment]
그렇다면 꼭 화면으로 확인할 필요는 없으니 postman을 써보길 추천드릴게요   앞으로 post, put delete 메서드 요청도 사용해야하는데 화면으로 테스트하기 쉽지 않을거에요
